# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebparserDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 4.0.0'
  pod 'webparser', :path=> '..'
  # Pods for WebparserDemo

  target 'WebparserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebparserDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
